# The URL the site will be built for
base_url = "https://dandellion.xyz"

title = "Daniel Olsen"
description = "Daniel Olsen's blog"

generate_feed = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "even"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
# Put all your custom variables here

even_title = "Daniel Olsen"

katex_enable = true
katex_auto_render = true
